# Generated by Django 4.2.8 on 2024-01-14 18:10

from django.db import migrations
import eticketing.models


class Migration(migrations.Migration):

    dependencies = [
        ('eticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', eticketing.models.CustomUserManager()),
            ],
        ),
    ]
